language: ruby
rvm:
  - 2.3.1
branches:
  only:
    - master
    - develop
script: bundle exec rspec --tag ~broken_in_ci
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec sqlite3 --version
  - bundle exec rake config
addons:
  code_climate:
    repo_token: ce328d44d99a09d03c1dac2198c731dc8bfd22374fefc1917ce528b25a06ec4e
notifications:
  slack:
    
    secure: >
      NPN5UAfze0ArE08cpxZlgZ0dN1s2FSeoKaJnf/zElBM+GrL4WDsGwUfgMc9yqIgc3aiDc1HHjzkNtqJynz2+bkMSBqtxzXteZ/Dz1hklXv6u2SCjuVCEyb+rzq488fN78gB5ohV9ovzAFuPm+T1b/vnXmSYBtJbnm8TRxgHHkM5x1gNE1FY+oZERByIiL+KSrG/k3pqFF1AtY3tt0hGDSMp1xhRblDdPUkq8FydApxUxI/dr5Aq8yN7QX4FWQvjm4Oka9+W16mIz7FiYo16r1BgSOWhsFEfub/PhTdD7AJyx3919xjvmrXZf5TVCYrxDmqPq4Ijgi9tgI2zxYyKyydB4U3yV+yGbM3zWFDHDKdX+iWdxkUl7iCZ3VXjvjpZj8WoFixQcOXwBq3HH5j9OEFZsgWhGa9cbvMvqfXKi23NCW1ybRVzbTO6GfjPi7GOByTKgBBf54wQPf4zD/GBehHrmGQV5ylWhPHlWYE5YmoKFrFczwbv9iUXIM+4ytMHYF+PcvLjVEPVOSLxw7F7d4ZE6hLpDKl9sXlZfoLpNYQNrlPBbFJEN/RBvUwX98Z2Ks+FEP2j28FSB3tnw4RsHCGrWmGeLL+K7UReASOXJY679sn9GlAtvNWO28MzFxAYOWxfSHNJO8jWtpBo7xxZrxw0RLr+vJlwsQFMwxXXLl7s=
